version: '3.8'
volumes:
    keys:
    ssl:
    acme-sh:
    acme-acc:
    zone:
services:
  dns:
    image: dns-privacy
    hostname: doh-server
    build:
      context: ./dns-privacy
    container_name: dns
    restart: on-failure:5
    # init: true
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    # env_file: .env
    environment:
      - CF_Email=${CF_EMAIL}
      - CF_Key=${CF_KEY}
      - CF_Token=${CF_TOKEN}
      - CF_Account_ID=${CF_ACCOUNT_ID}
      - CF_Zone_ID=${CF_ZONE_ID}
      - DOMAIN=${DOMAIN}
      - PROVIDER_NAME=${PROVIDER_NAME}
    volumes:
       - keys:/opt/encrypted-dns/keys
       - ssl:/opt/ssl
       - acme-sh:/root/.acme.sh
       - acme-acc:/acme.sh
       - zone:/etc/unbound/run
    ports:
      - "443:443/tcp"
      - "853:853/tcp"
      - "443:443/udp"
      - "853:853/udp"
    # sysctls:
    #   net.ipv4.tcp_congestion_control: bbr