name: haproxy
on:
  workflow_dispatch:
  push:
    paths:
      - 'haproxy/*'
jobs:
  build:
    name: Build & Push haproxy Container
    runs-on: ubuntu-latest
    env:
      APP: haproxy
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PACKAGE_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.APP }}
          file: ${{ env.APP }}/Dockerfile
          platforms: linux/386,linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/${{ env.APP }}:latest
            ${{ github.repository_owner }}/${{ env.APP }}:latest
